# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-22 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hedline', models.CharField(max_length=100)),
                ('rubrick', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=1000)),
                ('published', models.DateField()),
            ],
        ),
    ]
