# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-06-04 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_blog_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ul', models.CharField(max_length=100)),
                ('radio', models.CharField(max_length=100)),
            ],
        ),
    ]
