# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-07-29 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200615_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.IntegerField()),
                ('user2', models.IntegerField()),
                ('messages', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(default=11, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='test',
            name='ul',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
