# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-05-23 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='published',
        ),
    ]
